name: i18n_json
description: An alternative dart code generator for the vs-code plugin "vscode-flutter-i18n-json"
version: 0.9.0


environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  yaml: '>=2.0.0 <4.0.0'
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
