name: i18n_json
description: An alternative dart code generator for the vs-code plugin "vscode-flutter-i18n-json"
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  yaml: ^2.2.1
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
